"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['lut.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
'site_packages': True,
'packages': ['pandas', 'numpy']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)



